language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
    - composer selfupdate
    - composer install -n

script: phpunit --coverage-clover /tmp/coverage.xml

branches:
  only:
    - master
    - develop
